SERVER_WEBSOCKET_PORT: "8080"
SERVER_WEBSOCKET_CHECK_ORIGIN: "true"
SERVER_WEBSOCKET_MAX_CONN: "30000"
SERVER_WEBSOCKET_READ_BUFFER_SIZE: "10240"
SERVER_WEBSOCKET_WRITE_BUFFER_SIZE: "10240"
SERVER_WEBSOCKET_CONN_UNIQ_ID_HEADER: "x-user-id"
SERVER_WEBSOCKET_PING_INTERVAL_MS: 30000
SERVER_WEBSOCKET_PONG_WAIT_INTERVAL_MS: 60000
SERVER_WEBSOCKET_WRITE_WAIT_INTERVAL_MS: 5000
SERVER_WEBSOCKET_PINGER_SIZE: 1

WORKER_BUFFER_CHANNEL_SIZE: 5
WORKER_BUFFER_FLUSH_TIMEOUT_MS: 5000
WORKER_POOL_SIZE: 5
WORKER_KAFKA_DELIVERY_CHANNEL_SIZE: 100

EVENT_DISTRIBUTION_PUBLISHER_PATTERN: "clickstream-%s-log"

PUBLISHER_KAFKA_CLIENT_BOOTSTRAP_SERVERS: "kafka:9092"
PUBLISHER_KAFKA_CLIENT_ACKS: "1"
PUBLISHER_KAFKA_CLIENT_RETRIES: "2"
PUBLISHER_KAFKA_CLIENT_RETRY_BACKOFF_MS: "100"
PUBLISHER_KAFKA_CLIENT_STATISTICS_INTERVAL_MS: 5000
PUBLISHER_KAFKA_CLIENT_QUEUE_BUFFERING_MAX_MESSAGES: 100000
PUBLISHER_KAFKA_FLUSH_INTERVAL_MS: 1000

METRIC_STATSD_ADDRESS: ":8125"
METRIC_STATSD_FLUSH_PERIOD_MS: 100

LOG_LEVEL: "info"
