name: Test & Build

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: '1.14'
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Project
        run: make install-protoc; make setup
      - name: Invoking go test
        run: make test
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: '1.14'
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - uses: actions/checkout@v2
      - name: Build
        run: make all
